### ISSUE TITLE
Why use least square method?

### ISSUE THREAD

**Issue by sammyjan** [jim1993/Ardrone_indoor_slam#5]
Hello, this is a great job! Now I am learning SLAM and I am a  mere beginner.I want to know why you use least square method while many people are using Kalman filter method to obtain the real scale.

**Comment by haochihlin** [comment]
Hi
Thank you for being interested in this progect.
About the least square methods, well, because this demo was done almost 4 years ago.
At that time, there were various fusion algorithms for scale estimation.
In fact, the latter developing of this project was based on MSF_EKF (Error State KF) and got better results.

BTW, if you have any further questions, could you please change to following repo:
https://github.com/Hypha-ROS/hypharos_ardrone_navigation
Since this repo are not maintained anymore.

HaoChih, Lin

**Comment by sammyjan** [comment]
@haochihlin Thank you!
